/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package functional.java;

import io.vavr.collection.List;

import static io.vavr.API.*;
import static io.vavr.Patterns.*;

public class App {
    public List<Integer> list() {
        final var lst = List.of(1, 2, 3);
        final var head = lst.headOption();
        final var tail = lst.tailOption();
        final var match = Match(head).of(
            Case($Some($()), (x) -> x),
            Case($None(), () -> -1)
        );

        System.out.println(lst);
        System.out.println(head);
        System.out.println(tail);
        System.out.println(match);

        return lst.append(4);
    }

    public static void main(String[] args) {
        System.out.println(new App().list());
    }
}
